version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/navigator-admin-prod
    #destination: /home/ubuntu/magnus-uat
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
    - location: scripts/build.sh
      timeout: 1500
      runas: root
  ApplicationStart:
    - location: scripts/copy_to_target.sh
      timeout: 1500
      runas: root
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
    - location: scripts/delete_old.sh
      timeout: 300
      runas: root
