export enum StorageKeys {
  ONLINE_ID = "onlineId",
  QUOTE_ID = "quoteId",
  DIALER_ID = "dialerId",
  GET_QUOTE_FORM = "getQuoteForm",
  TELE_QUOTE_FORM = "teleQuoteForm",
  USER = "user",
  LEAD2PG = "proceedForPayment",
  HOMEPAGE_PLANTYPE = "homepagePlanType",
  VISIBLE_COLUMNS = "visibleColumns",
}

export enum EndPoints {
  ASSIGN_TO_INVESTIGATOR = "/api/FNI-work-flow/assignToInvestigator",
  AUTO_PRE_QC = "/api/Claims/autoPreQC",
  CAPTURE_INVESTIGATION_FINDINGS = "/api/fni-mobile-@captureInvestigationFindings",
  CAPTURE_RM_INVESTIGATION_FINDINGS = "/api/fni-mobile-@captureRMInvestigationFindings",
  CAPTURE_QA_FINDINGS = "/api/Claims/captureQAFindings",
  CASE_DETAIL = "/api/Claims/caseDetail",
  CASE_EVENT = "/api/Claims/caseEvent",
  CHANGE_TASK = "/api/Claims/changeTask",
  CHANGE_CLAIM_SUB_TYPE = "/api/Claims/changeClaimSubType",
  CITY = "/api/Claims/city",
  DASHBOARD_COUNTS = "/api/Claims/dashboardCounts",
  DASHBOARD_DATA = "/api/Claims/getData",
  EXTERNAL_INV_LIST = "/api/Claims/externalInvestigatorsList",
  EXPEDITE_CASE = "/api/Claims/expediteCase",
  FAILED_CASES = "/api/Claims/failedCases",
  FEED_DASHBOARD = "/api/FNI-work-flow/feedDashboard",
  GET_DISTRICTS = "/api/Claims/newStateDistrictMaster",
  GET_SIGNED_URL = "/api/Claims/getSignedUrl",
  HOSPITAL_PROVIDER = "/api/Claims/hospitalProviders",
  HOSPITAL_PROVIDERS = "/api/Claims/hospitalProviders",
  INVESTIGATORS = "/api/FNI-work-flow/investigator",
  NEW_CITY_MASTER = "/api/Claims/newCityMaster",
  NEW_PIN_CODE_MASTER = "/api/Claims/newPinCodeMaster",
  PIN_CODE = "/api/Claims/pinCode",
  PRE_QC_RETURN_THE_CASE = "/api/Claims/preQcReturnTheCase",
  REVERSE_API = "/api/Claims/FNIReverseApiCall",
  RUN_TRIAGE = "/api/FNI-work-flow/runTriagingLogic",
  STATES = "/api/Claims/states",
  UPLOAD_DASHBOARD_DATA = "/api/Claims/uploadClaimDetails",
  UPLOAD_TO_S3 = "/api/fni-mobile-@uploadToS3",
  UPDATE_CASE_DETAIL = "/api/fni-mobile-@updateCaseDetail",
  UPDATE_DASHBOARD_DATA = "/api/fni-mobile-@updateDashboardData",
  USER = "/api/Claims/user",
  USER_LOGIN = "/api/fni-auth/userLogin",
  USER_LOGOUT = "/api/Claims/userLogout",
  USER_MASTER = "/api/Claims/usersMaster",
  WDMS_DOC_DETAIL = "/api/Claims/wdmsDocs/docDetail",
  WDMS_DOC_CONTENT = "/api/Claims/wdmsDocs/docContent",
  ZONE_MASTER = "/api/Claims/zoneMaster",
  ZONE_STATE_MASTER = "/api/Claims/zoneStateMaster",

  // Maximus Endpoint
  GET_AUTH = "auth/getauthtoken",
  GET_CLAIM_DETAIL_BY_ID = "claim/getclaimdetialbyid",
  GET_CUSTOMER_POLICY_DETAIL = "policy/getcustomerpolicydetail",
  GET_CLAIM_OTHER_DETAILS = "claim/getclaimotherdetails",
  GET_CLAIM_HISTORY = "claim/getclaimhistory",
  GET_PROVIDER_DETAILS = "claim/getproviderdetails",
  GET_CONTRACT_DETAILS = "contract/getcontractalldetails",
  GET_APPLICATION_ID_DETAILS = "common/getpreissuancestatus",
  UPDATE_FNI_DETAILS = "claim/updatefnidetails",
  GET_DOCS_TOKEN = "generateToken",
  GET_DOCS_DETAIL = "getDocumentDetails",
  POST_DOC_STATUS = "postDocumentStatus",
}

export enum Databases {
  FNI = "FNI",
}

export enum FromEmails {
  DO_NOT_REPLY = "donotreply@nivabupa.com",
}
