const sampleCustomerPolicyDetail = {
  Status: "True",
  StatusMessage: "Success",
  CUSTOMERS: [
    {
      CUSTOMER_NUMBER: "30419342",
      PIVOTAL_CUSTOMER_ID: "2000078813",
      CUSTOMER_NAME: "Mr. Kanha Singh",
      PERMANENT_ADDRESS_1: "sdfsdfsdf",
      PERMANENT_ADDRESS_2: "sdfsdfsd",
      PERMANENT_ADDRESS_3: null,
      PERMANENT_ADDRESS_4: null,
      PERMANENT_ADDRESS_CITY: "Delhi",
      PERMANENT_ADDRESS_STATE: "Delhi",
      PERMANENT_ADDRESS_PIN_CODE: "110001",
      CURRENT_ADDRESS_1: "sdfsdfsdf",
      CURRENT_ADDRESS_2: "sdfsdfsd",
      CURRENT_ADDRESS_3: null,
      CURRENT_ADDRESS_4: null,
      CURRENT_ADDRESS_CITY: "Delhi",
      CURRENT_ADDRESS_STATE: "Delhi",
      CURRENT_ADDRESS_STATE_CODE: "0010",
      CURRENT_ADDRESS_CITY_CODE: "1100",
      CURRENT_ADDRESS_PIN_CODE: "110001",
      COMMUNICATION_ADDRESS: "C",
      PHONE_NO1: "8130179711",
      PHONE_NO2: null,
      PHONE_NO3: "8130179711",
      CUST_EMAIL: "dipika.lonkar@nivabupa.com",
      POLICY_NO: "30419342202200",
      DOB: "1967-04-04",
      PORTABILITY_FLAG: "N",
      PREVIOUS_INSURANCE_COMPANY: null,
      INSURED_SINCE: "2022-11-10",
      KYCDetails: {
        KYC_DONE: "Y",
        KYC_IDENTITY_MASTER: "Y_OVD_OTH",
        KYC_ADDRESS_MASTER: "Y_OVD_OTH",
        KYC_IDENTITY_RECORD_NUMBER: null,
        KYC_ADDRESS_RECORD_NUMBER: null,
        CKYC_NUMBER: null,
      },
      NomineeDetails: {
        Name: "sdfsdf cvbcvb sfgnfgfg",
        Relationship: "Father",
        DOB: "1979-05-08",
        Address: "sdfsdfsdf; sdfsdfsd; Delhi; Delhi;110001",
        RelationShipID: "F",
      },
      CONTRACTS: [
        {
          POLICY_NO: "30419342202200",
          EFFECTIVE_DATE_OF_CONTRACT: "2022-11-10",
          CONTRACT_TERMINATION_DATE: "2024-11-09",
          NET_PREMIUM_AMOUNT: "118185",
          CONT_NO: "30419342",
          PLAN_ID: "2768464",
          APP_NO: "821100417660        ",
          SUM_INSURED: "750000",
          RENEWAL_CHECK: "0",
          CONTRACT_ACCRUED_NCB: " ",
          HEALTH_COACH: null,
          PAOPTED: null,
          PA_SUM_INSURED: "0",
          CI_SUM_INSURED: null,
          Coverage_Type: "FLOATER",
          Hosital_cash: "Y ",
          Safeguard: "Y",
          SourceSystem: "M",
          COVER_SUB_TYPE: "FLOATER",
          AGENT_NAME: "VANDANA KALRA - DEL0100242",
          AGENT_CODE: "DEL0100242",
        },
      ],
      PLANS: [
        {
          PLAN_ID: "2768464",
          PLAN_DESC: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
          PLAN_LIMIT: "750000",
          FLOATER_LIMIT: "0",
          TOTAL_INDIVIDUAL_LIMIT: " ",
          PROD_TYPE: "IIRA",
          VARIANT: null,
          PRODUCT_NAME: "ReAssure",
          CONT_NO: "30419342",
          CARD_TYPE: "Floater Coverage basis",
          VER_NUM: "1",
          ADULT_COVERED: "2",
          CHILD_COVERED: "1",
        },
      ],
      MEMBERS: [
        {
          MEMBER_ID: "10497955",
          MEMBERSHIP_NO: "10497955",
          MEMBER_NAME: "Mr. Kanha Singh",
          MEMBER_DATE_OF_BIRTH: "1967-04-04",
          GENDER: "Male",
          MEMBER_STATUS: "Active",
          MEMBER_EFFECTIVE_DATE: "2022-11-10",
          MEMBER_REGISTRATION_DATE: "2022-11-10",
          PLAN_ID: "2768464",
          CONT_NO: "30419342",
          RELATION: "Self",
          PROPMEM: "M",
          LOADING_PER_MEMBER: "20",
          MEMBER_NCB: "375000",
          ISHEALTH_COACH: null,
          ISPAOPTED: "N",
          MOBILE_NO: "8130179711",
          CUST_EMAIL: "dipika.lonkar@nivabupa.com",
          IsMemberAdult: "No",
          GoQiiID: null,
          MGID: " ",
          PractoID: " ",
          COI: null,
          INSURE_MEMBER_HEIGHT: "170",
          INSURE_MEMBER_WEIGHT: "70",
          OCCUPATION: "Others",
        },
        {
          MEMBER_ID: "10497956",
          MEMBERSHIP_NO: "10497956",
          MEMBER_NAME: "Mrs. sdsdf dfdf",
          MEMBER_DATE_OF_BIRTH: "1972-06-12",
          GENDER: "Female",
          MEMBER_STATUS: "Active",
          MEMBER_EFFECTIVE_DATE: "2022-11-10",
          MEMBER_REGISTRATION_DATE: "2022-11-10",
          PLAN_ID: "2768464",
          CONT_NO: "30419342",
          RELATION: "Spouse",
          PROPMEM: "M",
          LOADING_PER_MEMBER: "0",
          MEMBER_NCB: "375000",
          ISHEALTH_COACH: null,
          ISPAOPTED: "N",
          MOBILE_NO: "8130179711",
          CUST_EMAIL: "dipika.lonkar@nivabupa.com",
          IsMemberAdult: "No",
          GoQiiID: null,
          MGID: " ",
          PractoID: " ",
          COI: null,
          INSURE_MEMBER_HEIGHT: "170",
          INSURE_MEMBER_WEIGHT: "70",
          OCCUPATION: "Others",
        },
        {
          MEMBER_ID: "10497957",
          MEMBERSHIP_NO: "10497957",
          MEMBER_NAME: "Mr. jhjkh iuuiyuy",
          MEMBER_DATE_OF_BIRTH: "2010-06-15",
          GENDER: "Male",
          MEMBER_STATUS: "Active",
          MEMBER_EFFECTIVE_DATE: "2022-11-10",
          MEMBER_REGISTRATION_DATE: "2022-11-10",
          PLAN_ID: "2768464",
          CONT_NO: "30419342",
          RELATION: "Child",
          PROPMEM: "M",
          LOADING_PER_MEMBER: "0",
          MEMBER_NCB: "375000",
          ISHEALTH_COACH: null,
          ISPAOPTED: "N",
          MOBILE_NO: "8130179711",
          CUST_EMAIL: "dipika.lonkar@nivabupa.com",
          IsMemberAdult: "No",
          GoQiiID: null,
          MGID: " ",
          PractoID: " ",
          COI: null,
          INSURE_MEMBER_HEIGHT: "170",
          INSURE_MEMBER_WEIGHT: "70",
          OCCUPATION: "Others",
        },
      ],
    },
  ],
};

const sampleClaimOtherDetails = {
  Status: "true",
  StatusMessage: "Success",
  PolicyNo: "30419342202200",
  PolicyClaimsOther: {
    MemberDetails: {
      Member_Name: "Mrs.sdsdf dfdf",
      membershipId: "0022111022",
      COI: "",
      ClaimDetailsOther: {
        NOTES: "",
        DIAG_CODE: "R50                 ",
        DIAG_CODE2: "",
        DIAG_CODE3: "",
        PROC_CODE: "",
        PROC_CODE2: "",
        FIRST_DIAG_DATE: "01-JAN-2024",
        HOSPITALIZAITONTYPE: "Planned",
        WAIVE_REASON: "",
        DIAG_NOTE: "",
        REJ_QTY: "",
        REJ_AMT: "",
        REJ_DESC: "",
        REJ_REASON: "",
        FILE_REC_DATE: "",
        REPORT_SHARING_DATE: "",
        FINAL_OUTCOME: "",
        EXECUTIVE_SUMMARY: "",
        RECOMMENDATION: "",
        PROV_NAME: "Max Hospital.",
        FRAUD_STATUS: "None",
        TERM_DATE: "",
        UNRECOGNIZED_IND: "N",
        DEACTIVE: "",
        NETWORK_EXIST: "Y",
        NETWORK_TYPE: "Out-network",
        Claim_Status: "WIP",
        ClaimStatusCode: "W",
        DeductionDetailsKey: "",
        FRAUDTYPE: "",
        FRAUDREASON: "",
        DiasnosisDetails: "",
        Exclusionremark: "",
      },
      FNI: {
        Main_Claim: "test",
        Line_Of_Treatement: "test",
        FRAUD_INDICATORS: [
          {
            FRAUD_INDICATOR_DESC: "Claim in the first year of policy issuance.",
            Values: {
              CL_Selected: "TRUE",
              FI_Selected: "FALSE",
            },
          },
          {
            FRAUD_INDICATOR_DESC: "Fraud Prone Area",
            Values: {
              CL_Selected: "TRUE",
              FI_Selected: "FALSE",
            },
          },
        ],
        Other_Remarks: "need to rule out for investigation",
      },
    },
  },
};

const sampleContractDetail = {
  CONTRACTS: [
    {
      POLICY_NO: "30419340202200",
      EFFECTIVE_DATE_OF_CONTRACT: "2022-11-10",
      CONTRACT_TERMINATION_DATE: "2025-11-09",
      NET_PREMIUM_AMOUNT: "89075",
      CONT_NO: "30419340",
      PLAN_ID: "2741811",
      APP_NO: "821100417623",
      SUM_INSURED: "2000000",
      RENEWAL_CHECK: "0",
      CONTRACT_ACCRUED_NCB: " ",
      HEALTH_COACH: null,
      PAOPTED: "N",
      PA_SUM_INSURED: "0",
      CI_SUM_INSURED: null,
      Coverage_Type: "FLOATER",
      Hosital_cash: "Y",
      Safeguard: "Y",
      SourceSystem: "M",
      COVER_SUB_TYPE: "FLOATER",
      AGENT_NAME: "VANDANA KALRA - DEL0100242",
      AGENT_CODE: "DEL0100242",
    },
  ],
  PLANS: [
    {
      PLAN_ID: "2741811",
      PLAN_DESC: "ReAssure Floater 20L HC Z1 2A1C",
      PLAN_LIMIT: "2000000",
      FLOATER_LIMIT: "0",
      TOTAL_INDIVIDUAL_LIMIT: " ",
      PROD_TYPE: "IIRA",
      VARIANT: null,
      PRODUCT_NAME: "ReAssure",
      CONT_NO: "30419340",
      CARD_TYPE: "Floater Coverage basis",
      VER_NUM: "1",
      ADULT_COVERED: "2",
      CHILD_COVERED: "1",
    },
  ],
  MEMBERS: [
    {
      MEMBER_ID: "10497950",
      MEMBERSHIP_NO: "10497950",
      MEMBER_NAME: "Mr. Tilang Jain",
      MEMBER_DATE_OF_BIRTH: "1992-05-07",
      GENDER: "Male",
      MEMBER_STATUS: "Active",
      MEMBER_EFFECTIVE_DATE: "2022-11-10",
      MEMBER_REGISTRATION_DATE: "2022-11-10",
      PLAN_ID: "2741811",
      CONT_NO: "30419340",
      RELATION: "Self",
      PROPMEM: "M",
      LOADING_PER_MEMBER: "0",
      MEMBER_NCB: "0.0",
      ISHEALTH_COACH: null,
      ISPAOPTED: "N",
      MOBILE_NO: "8130179711",
      CUST_EMAIL: "dipika.lonkar@nivabupa.com",
      IsMemberAdult: "No",
      GoQiiID: null,
      MGID: " ",
      PractoID: " ",
      COI: null,
      INSURE_MEMBER_HEIGHT: "170",
      INSURE_MEMBER_WEIGHT: "70",
      OCCUPATION: "Others",
    },
    {
      MEMBER_ID: "10497951",
      MEMBERSHIP_NO: "10497951",
      MEMBER_NAME: "Mrs. kalia Jain",
      MEMBER_DATE_OF_BIRTH: "1992-04-07",
      GENDER: "Female",
      MEMBER_STATUS: "Active",
      MEMBER_EFFECTIVE_DATE: "2022-11-10",
      MEMBER_REGISTRATION_DATE: "2022-11-10",
      PLAN_ID: "2741811",
      CONT_NO: "30419340",
      RELATION: "Spouse",
      PROPMEM: "M",
      LOADING_PER_MEMBER: "20",
      MEMBER_NCB: "0.0",
      ISHEALTH_COACH: null,
      ISPAOPTED: "N",
      MOBILE_NO: "8130179711",
      CUST_EMAIL: "dipika.lonkar@nivabupa.com",
      IsMemberAdult: "No",
      GoQiiID: null,
      MGID: " ",
      PractoID: " ",
      COI: null,
      INSURE_MEMBER_HEIGHT: "170",
      INSURE_MEMBER_WEIGHT: "70",
      OCCUPATION: "Others",
    },
  ],
};

const sampleClaimDetail = {
  Status: "true",
  StatusMessage: "Success",
  PolicyNo: "30419342202200",
  PolicyClaims: {
    Member_Name: "Mrs.sdsdf dfdf",
    membershipId: "0022111022",
    COI: null,
    ClaimDetail: {
      Illness: "R50                 ",
      Claim_Number: "P_48458",
      Claim_Type: "In-patient",
      Hospitilization_Date: "04-JAN-2024",
      Discharge_Date: "05-JAN-2024",
      Procedure_Code: null,
      Billed_Amount: "1000000",
      Approved_Amount: "1000000",
      Claims_Status: "WIP",
      Claim_Reported_Date: "16-JAN-2024",
      Contract_Number: "30419342",
      Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
      Sum_Insured: "750000",
      Provider_Name: "Max Hospital.",
      Claim_Decision_Date: "16-JAN-2024",
      ClaimStatusCode: "W",
    },
  },
};

const sampleClaimHistory = {
  Status: "true",
  StatusMessage: "Success",
  PolicyNo: "30419342202200",
  PolicyClaims: {
    MemberList: [
      {
        Member_Name: "Mr.Kanha Singh",
        memberNo: "0022111012",
        membershipId: "10497955",
        COI: "",
        ClaimHistory: [
          {
            Illness: "I24                 ",
            Claim_Number: "P_47654",
            Claim_Type: "In-patient",
            Hospitilization_Date: "29-JUL-2023",
            Discharge_Date: "30-JUL-2023",
            Procedure_Code: "",
            Billed_Amount: "10000",
            Approved_Amount: "10000",
            Claims_Status: "Approved",
            Claim_Reported_Date: "29-JUL-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name:
              "ETERNAL HEARTCARE CENTRE & RESEARCH INSTITUTE PVT. LTD.",
            Claim_Decision_Date: "29-JUL-2023",
            Interim_Status: "Approved",
            Final_Status: "Approved",
            Provider_Code: "32836 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "A",
          },
          {
            Illness: "J20.9               ",
            Claim_Number: "P_47669",
            Claim_Type: "In-patient",
            Hospitilization_Date: "05-AUG-2023",
            Discharge_Date: "05-AUG-2023",
            Procedure_Code: "",
            Billed_Amount: "40590",
            Approved_Amount: "1200",
            Claims_Status: "WIP",
            Claim_Reported_Date: "01-AUG-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "Ananthapuri Hospitals & Research Institute",
            Claim_Decision_Date: "01-AUG-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20843 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
          {
            Illness: "J22                 ",
            Claim_Number: "P_47701",
            Claim_Type: "In-patient",
            Hospitilization_Date: "02-AUG-2023",
            Discharge_Date: "02-AUG-2023",
            Procedure_Code: "",
            Billed_Amount: "2",
            Approved_Amount: "900",
            Claims_Status: "WIP",
            Claim_Reported_Date: "02-AUG-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "METRO HEART INSTITUTE WITH MULTISPECIALITY",
            Claim_Decision_Date: "02-AUG-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20040 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
          {
            Illness: "K35                 ",
            Claim_Number: "P_47455",
            Claim_Type: "In-patient",
            Hospitilization_Date: "08-JUL-2023",
            Discharge_Date: "08-JUL-2023",
            Procedure_Code: "",
            Billed_Amount: "63900",
            Approved_Amount: "571219.5",
            Claims_Status: "WIP",
            Claim_Reported_Date: "08-JUL-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "SATGURU PRATAP SINGH APOLLO HOSPITALS",
            Claim_Decision_Date: "08-JUL-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20453 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
          {
            Illness: "K80                 ",
            Claim_Number: "P_47656",
            Claim_Type: "In-patient",
            Hospitilization_Date: "31-JUL-2023",
            Discharge_Date: "31-JUL-2023",
            Procedure_Code: "",
            Billed_Amount: "4500",
            Approved_Amount: "",
            Claims_Status: "WIP",
            Claim_Reported_Date: "29-JUL-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name:
              "ETERNAL HEARTCARE CENTRE & RESEARCH INSTITUTE PVT. LTD.",
            Claim_Decision_Date: "29-JUL-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "32836 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
          {
            Illness: "K80                 ",
            Claim_Number: "R_84539",
            Claim_Type: "In-patient",
            Hospitilization_Date: "10-NOV-2022",
            Discharge_Date: "10-NOV-2022",
            Procedure_Code: "",
            Billed_Amount: "10000",
            Approved_Amount: "",
            Claims_Status: "Not Payable",
            Claim_Reported_Date: "11-JAN-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "Max Hospital.",
            Claim_Decision_Date: "11-JAN-2023",
            Interim_Status: "Not Payable",
            Final_Status: "Not Payable",
            Provider_Code: "20007 ",
            TreatingDoctorName: "",
            TreatingDoctorID: "",
            ClaimStatusCode: "RJ                  ",
          },
        ],
      },
      {
        Member_Name: "Mrs.sdsdf dfdf",
        memberNo: "0022111022",
        membershipId: "10497956",
        COI: "",
        ClaimHistory: [
          {
            Illness: "A09                 ",
            Claim_Number: "P_47682",
            Claim_Type: "In-patient",
            Hospitilization_Date: "01-AUG-2023",
            Discharge_Date: "02-AUG-2023",
            Procedure_Code: "",
            Billed_Amount: "5000",
            Approved_Amount: "2500",
            Claims_Status: "Approved",
            Claim_Reported_Date: "01-AUG-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "Fortis Flt. Lt. Rajan Dhall Hospital",
            Claim_Decision_Date: "01-AUG-2023",
            Interim_Status: "Approved",
            Final_Status: "Approved",
            Provider_Code: "20234 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "A",
          },
          {
            Illness: "R50                 ",
            Claim_Number: "P_48458",
            Claim_Type: "In-patient",
            Hospitilization_Date: "04-JAN-2024",
            Discharge_Date: "05-JAN-2024",
            Procedure_Code: "",
            Billed_Amount: "1000000",
            Approved_Amount: "1000000",
            Claims_Status: "WIP",
            Claim_Reported_Date: "16-JAN-2024",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "Max Hospital.",
            Claim_Decision_Date: "16-JAN-2024",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20007 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
        ],
      },
      {
        Member_Name: "Mr.jhjkh iuuiyuy",
        memberNo: "0022111032",
        membershipId: "10497957",
        COI: "",
        ClaimHistory: [
          {
            Illness: "A90                 ",
            Claim_Number: "P_47659",
            Claim_Type: "In-patient",
            Hospitilization_Date: "31-JUL-2023",
            Discharge_Date: "31-JUL-2023",
            Procedure_Code: "",
            Billed_Amount: "60011",
            Approved_Amount: "7950",
            Claims_Status: "WIP",
            Claim_Reported_Date: "31-JUL-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "YASHODA SUPER SPECIALITY HOSPITAL, Ranga Reddy",
            Claim_Decision_Date: "31-JUL-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20348 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
          {
            Illness: "J20.9               ",
            Claim_Number: "P_47595",
            Claim_Type: "In-patient",
            Hospitilization_Date: "24-JUL-2023",
            Discharge_Date: "25-JUL-2023",
            Procedure_Code: "",
            Billed_Amount: "5000",
            Approved_Amount: "5000",
            Claims_Status: "WIP",
            Claim_Reported_Date: "25-JUL-2023",
            Contract_Number: "30419342",
            Product_Type: "ReAssure Floater 7.5L HC Z1 AC 15K DM P 2A1C",
            Sum_Insured: "750000",
            Provider_Name: "Ananthapuri Hospitals & Research Institute",
            Claim_Decision_Date: "25-JUL-2023",
            Interim_Status: "WIP",
            Final_Status: "WIP",
            Provider_Code: "20843 ",
            TreatingDoctorName: "NA",
            TreatingDoctorID: "NA",
            ClaimStatusCode: "W",
          },
        ],
      },
    ],
  },
};

const getDocumentDetails = {
  Status: "Success",
  UniqueIdentifier: "003",
  WorkItemID: "NB-0000000000000437714-Process",
  CaseTypeID: "30434705202400",
  Documents: [
    {
      Document_Name: "3.jpg.JPG",
      Document_Index: "1741009",
      Document_Class: "Form60",
      Document_Date: "2024-01-12 10:47:49.97",
    },
    {
      Document_Name: "5.jpg.JPG",
      Document_Index: "1741117",
      Document_Class: "Other",
      Document_Date: "2024-01-12 10:49:49.54",
    },
    {
      Document_Name: "4.jpg.JPG",
      Document_Index: "1741148",
      Document_Class: "Photo",
      Document_Date: "2024-01-12 10:51:10.337",
    },
    {
      Document_Name: "Chq_IMG-20240228-WA0000.jpg.JPG",
      Document_Index: "1786397",
      Document_Class: "VAS_Claims",
      Document_Date: "2024-03-04 15:55:36.957",
    },
    {
      Document_Name: "Inv_last discharge summary.pdf.PDF",
      Document_Index: "1786401",
      Document_Class: "VAS_Claims",
      Document_Date: "2024-03-04 15:55:39.87",
    },
    {
      Document_Name: "Lab_Rep_lab test.pdf.PDF",
      Document_Index: "1786405",
      Document_Class: "VAS_Claims",
      Document_Date: "2024-03-04 15:55:43.7",
    },
    {
      Document_Name: "Pre_prescription.pdf.PDF",
      Document_Index: "1786409",
      Document_Class: "VAS_Claims",
      Document_Date: "2024-03-04 15:55:48.337",
    },
  ],
};

const generateDocToken = {
  token:
    "Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJzb2Z0dGVrSldUIiwic3ViIjoiMjhhZHNlZ2hqZ2Rzam1hcmNoZHdkd2lkajFqaDloamg5aGo5aGo2IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxMzk0MTg5NiwiZXhwIjoxNzEzOTQyMTk2fQ.EuTIfpADyQ-KiYdwteuKSMb_Qtg9fWzB20J2Y1YqP8S-HaSy5qBIYhvVieAhh7eqoLNGXliZQ5qoli1Z3n7sMA",
};

const postDocumentStatus = {
  status: "Success",
  Message: "SUCCESS",
  DocContent: "",
  UniqueIdentifier: "",
};

const getFniData = {
  Status: "True",
  StatusMessage: "Success",
  ClaimsData: [
    {
      Claims: "R_85091",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A1-Surg ops, incl pre & post operative care",
        },
      ],
    },
    {
      Claims: "R_84935",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A5-Patho., X-rays, diag. tests & therapies",
        },
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A4-Theatre charges and intensive care",
        },
      ],
    },
    {
      Claims: "R_84911",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A1-Surg ops, incl pre & post operative care",
        },
      ],
    },
    {
      Claims: "R_84907",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A5-Patho., X-rays, diag. tests & therapies",
        },
      ],
    },
    {
      Claims: "R_84622",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A5-Patho., X-rays, diag. tests & therapies",
        },
      ],
    },
    {
      Claims: "R_77193",
      SourceSystem: "M",
      ClaimsBenefits: [
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A7-Hospital Accommodation",
        },
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A9-Others",
        },
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A4-Theatre charges and intensive care",
        },
        {
          Benefit_Type: "A-In-patient Hospitalization",
          Benefit_Head: "A3-Physicians fees",
        },
      ],
    },
  ],
};

const getClaimFniDetails = {
  Status: "true",
  StatusMessage: "Success",
  PolicyNo: "30118640201200",
  PolicyClaimsOther: {
    ClaimFNIDetails: {
      Member_Name: "Ms.ANNAPURNA NEKKANTI",
      membershipId: "12071015",
      COI: "",
      FNI: {
        SR_NUMBER: "",
        Recommendations: "",
        Executive_Summary: "",
        Other_Remarks:
          "1. POLICY IS 5 DAYS OLD.\r\n2. HTN SINCE 2-3 MONTHS\r\n3.ADMITTED WITH C/O SEIZURES, H/O OF SIMILAR EPISODE 9 YRS BACK.\r\n4. NEED TO RULE OUT PED.",
        FRAUD_INDICATORS: [
          {
            FRAUD_INDICATOR_DESC: "Others",
            Values: {
              CL_Selected: "TRUE",
              FI_Selected: "TRUE",
            },
          },
          {
            FRAUD_INDICATOR_DESC:
              "Possible non disclosure/ misrepresentation of material facts.",
            Values: {
              CL_Selected: "TRUE",
              FI_Selected: "TRUE",
            },
          },
        ],
      },
    },
  },
};

const getMemberBenefitCover = {
  Status: "true",
  StatusMessage: "Success",
  PolicyNo: "50297100202200",
  MemberBenefitCover: {
    Member_Name: "Mr.NARESH KUMAR",
    membershipId: "0004404010",
    COI: "113004049663",
    Benefit_Covers: [
      {
        Benefit_Type: "02A - Pre and Post Hospitalization Medical Expenses",
        Benefit_Type_Indicator: "Y",
      },
      {
        Benefit_Type: "04A - Domiciliary Hospitalization",
        Benefit_Type_Indicator: "Y",
      },
      {
        Benefit_Type: "05A - Organ Transplant",
        Benefit_Type_Indicator: "Y",
      },
      {
        Benefit_Type: "21A - Sub-limit on specified illness/conditions",
        Benefit_Type_Indicator: "Y",
      },
      {
        Benefit_Type: "00A - In - patient Hospitalization",
        Benefit_Type_Indicator: "Y",
      },
      {
        Benefit_Type: "01A - Day Care Treatment",
        Benefit_Type_Indicator: "Y",
      },
    ],
  },
};
